// GENERATED by test/balance/run.ts (80 smart-policy runs). Do not hand-edit.

/** Score at each 5th percentile, 0..100. */
export const scorePercentiles: number[] = [2947,4218,4681,5687,5893,6083,6110,6138,6339,6435,7324,7999,8713,9197,10008,10274,10982,11351,11909,13232,15804];

export function percentileFor(score: number): number {
  let p = 0;
  for (let i = 0; i < scorePercentiles.length; i++) {
    if (score >= scorePercentiles[i]!) p = i * 5;
  }
  return p;
}
