// Ports the hand-written prose content from the Opus/V1 repo into typed TS
// data modules under src/content/. The prose is copied VERBATIM — this script
// exists so no word gets mistyped by a human (or a model) along the way.
//
// Run: node tools/port-content.mjs
// Reads: ../Primal-Chase-Opus/js/{encounters,monologue,narrative}.js
// Writes: src/content/*.ts (generated files, do not hand-edit)

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';
import vm from 'node:vm';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const opus = resolve(root, '..', 'Primal-Chase-Opus', 'js');
const outDir = join(root, 'src', 'content');
mkdirSync(outDir, { recursive: true });

function load(file, exportExpr) {
  const src = readFileSync(join(opus, file), 'utf8');
  const context = vm.createContext({ window: undefined, Math, Set, console });
  vm.runInContext(`${src}\n;globalThis.__EXPORT = ${exportExpr};`, context, { filename: file });
  return context.__EXPORT;
}

// ---- serialization: JSON for data, verbatim source for functions ----

const fnSources = [];

function toPlaceholders(value) {
  if (typeof value === 'function') {
    fnSources.push(value.toString());
    return `@@FN_${fnSources.length - 1}@@`;
  }
  if (Array.isArray(value)) return value.map(toPlaceholders);
  if (value && typeof value === 'object') {
    const out = {};
    for (const [k, v] of Object.entries(value)) out[k] = toPlaceholders(v);
    return out;
  }
  return value;
}

function emit(value) {
  let json = JSON.stringify(toPlaceholders(value), null, 2);
  json = json.replace(/"@@FN_(\d+)@@"/g, (_, i) => {
    let src = fnSources[Number(i)];
    // The one pressure condition that peeks at engine state: route through ctx.
    if (src.includes('Encounters._usedOldTerritory')) {
      src = src
        .replace('Encounters._usedOldTerritory', 'ctx.usedOldTerritory')
        .replace(/^\((state)\)/, '(state, ctx)');
    }
    return src;
  });
  return json;
}

function header(source) {
  return `// GENERATED by tools/port-content.mjs from Primal-Chase-Opus/js/${source}\n` +
         `// Prose is verbatim V1/Opus content. Do not hand-edit — re-run the porter.\n\n`;
}

function keysOf(list) {
  const keys = new Set();
  for (const item of list) for (const k of Object.keys(item)) keys.add(k);
  return [...keys].join(', ');
}

// ---- encounters ----

const E = load('encounters.js', 'Encounters');
const collections = [
  ['terrains', 'TerrainEntry'],
  ['opportunities', 'OpportunityEntry'],
  ['pressures', 'PressureEntry'],
  ['signatures', 'SignatureEntry'],
  ['rares', 'SignatureEntry']
];
let encOut = header('encounters.js') +
  `import type { TerrainEntry, OpportunityEntry, PressureEntry, SignatureEntry } from './types';\n`;
for (const [key, type] of collections) {
  encOut += `\nexport const ${key}: ${type}[] = ${emit(E[key])};\n`;
  console.log(`${key}: ${E[key].length} entries; keys: ${keysOf(E[key])}`);
}
writeFileSync(join(outDir, 'encounters.ts'), encOut);

// ---- monologue ----

const M = load('monologue.js', 'Monologue');
console.log(`monologue fragments: ${M.fragments.length}; keys: ${keysOf(M.fragments)}`);
writeFileSync(join(outDir, 'monologue.ts'),
  header('monologue.js') +
  `import type { MonologueFragment } from './types';\n\n` +
  `export const fragments: MonologueFragment[] = ${emit(M.fragments)};\n`);

// ---- narrative ----

const N = load('narrative.js', 'NARRATIVE');
console.log(`narrative: ${N.intros.length} intros; deaths: ${Object.keys(N.deaths).join(', ')}`);
writeFileSync(join(outDir, 'narrative.ts'),
  header('narrative.js') +
  `import type { DeathCause } from './types';\n\n` +
  `export const intros: string[][] = ${emit(N.intros)};\n\n` +
  `export const deaths: Record<DeathCause, string[]> = ${emit(N.deaths)};\n`);

console.log('\nPorted to src/content/.');
